# Generated by Django 5.1.1 on 2024-10-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admindetails',
            old_name='Username',
            new_name='username',
        ),
    ]
